apiVersion: v2
name: roundtable-operator
description: Knights of the Round Table â€” A Kubernetes Operator for Multi-Agent AI Orchestration
type: application
version: 0.2.0
appVersion: "1.0.0"
keywords:
  - ai
  - agents
  - operator
  - multi-agent
  - orchestration
home: https://github.com/dapperdivers/roundtable
sources:
  - https://github.com/dapperdivers/roundtable
maintainers:
  - name: dapperdivers
