apiVersion: ai.roundtable.io/v1alpha1
kind: Knight
metadata:
  labels:
    app.kubernetes.io/name: roundtable-operator
    app.kubernetes.io/managed-by: kustomize
  name: knight-sample
spec:
  # TODO(user): Add fields here
